<?php 
define('CNF_APPNAME','SchoolEdge');
define('CNF_APPADDRESS','SchoolEdge');
define('CNF_APPEMAIL','SchoolEdge@gmail.com');
define('CNF_APPNO','SchoolEdge');
define('CNF_FRONT','true');
define('CNF_DATEFORMAT','Y-d-m');
define('CNF_CURRENCY','$');
?>